server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/otbs
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: oubaidloukil@gmail.com
    password: zhgpqulhjrogvqbd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: your-secret-key
  expiration: 86400000 # Token expiration time in milliseconds (e.g., 24 hours)
  header: Authorization
  prefix: Bearer



